zx.plugins.install {
  { name = 'folke/tokyonight.nvim', options = {{'branch', 'main'}},},
  { name = 'nvim-treesitter/nvim-treesitter', options = {{'do', ':TSUpdate'}}, },
  { name = 'skywind3000/asyncrun.vim', },
  { name = 'nvim-lua/plenary.nvim', },
  { name = 'kyazdani42/nvim-web-devicons', },
  { name = 'nvim-lualine/lualine.nvim', },
  { name = 'romgrk/barbar.nvim', },
  { name = 'dense-analysis/ale', },
  { name = 'Pocco81/AutoSave.nvim', },
  { name = 'aperezdc/vim-template', },
  { name = 'hotoo/pangu.vim', options = {{'for', 'markdown'}}, },

--  { name = 'tamago324/lir.nvim', },
--  { name = 'hrsh7th/vim-vsnip', },
--  { name = 'hrsh7th/vim-vsnip-integ', },
--  { name = 'hrsh7th/cmp-vsnip', },
--  { name = 'hrsh7th/vim-vsnip', },
--  { name = 'neovim/nvim-lspconfig', },
--  { name = 'hrsh7th/nvim-cmp', },
--  { name = 'williamboman/nvim-lsp-installer', },
--  { name = 'hrsh7th/cmp-nvim-lsp', },
--  { name = 'hrsh7th/cmp-buffer', },
--  { name = 'hrsh7th/cmp-path', },
--  { name = 'hrsh7th/cmp-cmdline', },
--  { name = 'lukas-reineke/indent-blankline.nvim', },
--  { name = 'L3MON4D3/LuaSnip', },
}
